"""Export bitmap fonts FONT_RU and FONT_USTAV from art/ui/src/fonts_ru.py to src/data/font_ru.js.
Run: python3 tools/export_font.py   (from prototype folder). Read-only use of art sources."""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "art", "ui", "src"))
sys.dont_write_bytecode = True
from fonts_ru import FONT_RU, FONT_USTAV


def pack(font):
    g = {ch: ["".join("#" if v else "." for v in row) for row in a] for ch, a in font["glyphs"].items()}
    d = {"h": font["h"], "sp": font["sp"], "glyphs": g}
    for k in ("cap", "top"):
        if k in font:
            d[k] = font[k]
    return d


out = os.path.join(HERE, "..", "src", "data", "font_ru.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/export_font.py from art/ui/src/fonts_ru.py (FONT_RU, FONT_USTAV). Do not edit.\n")
    f.write("export const FONT_RU = " + json.dumps(pack(FONT_RU), ensure_ascii=False) + ";\n")
    f.write("export const FONT_USTAV = " + json.dumps(pack(FONT_USTAV), ensure_ascii=False) + ";\n")
print("fonts ->", out)
